title: Icepick
description: a weapon of mass user protection
url: https://icepicklicense.org
plugins:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- README.md
defaults:
  - scope:
      path: _versions
    values:
      layout: version
collections:
  versions:
    output: true
  projects:
    output: true
